# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 502)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(209, 209, 209);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.push_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_1.sizePolicy().hasHeightForWidth())
        self.push_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_1.setFont(font)
        self.push_1.setObjectName("push_1")
        self.buttons = QtWidgets.QButtonGroup(MainWindow)
        self.buttons.setObjectName("buttons")
        self.buttons.addButton(self.push_1)
        self.gridLayout_7.addWidget(self.push_1, 7, 0, 1, 1)
        self.push_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_4.sizePolicy().hasHeightForWidth())
        self.push_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_4.setFont(font)
        self.push_4.setObjectName("push_4")
        self.buttons.addButton(self.push_4)
        self.gridLayout_7.addWidget(self.push_4, 6, 0, 1, 1)
        self.push_plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_plus.sizePolicy().hasHeightForWidth())
        self.push_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_plus.setFont(font)
        self.push_plus.setObjectName("push_plus")
        self.buttons.addButton(self.push_plus)
        self.gridLayout_7.addWidget(self.push_plus, 8, 3, 1, 1)
        self.push_multiply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_multiply.sizePolicy().hasHeightForWidth())
        self.push_multiply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_multiply.setFont(font)
        self.push_multiply.setObjectName("push_multiply")
        self.buttons.addButton(self.push_multiply)
        self.gridLayout_7.addWidget(self.push_multiply, 6, 3, 1, 1)
        self.push_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_2.sizePolicy().hasHeightForWidth())
        self.push_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_2.setFont(font)
        self.push_2.setObjectName("push_2")
        self.buttons.addButton(self.push_2)
        self.gridLayout_7.addWidget(self.push_2, 7, 1, 1, 1)
        self.push_ac = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_ac.sizePolicy().hasHeightForWidth())
        self.push_ac.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_ac.setFont(font)
        self.push_ac.setObjectName("push_ac")
        self.buttons.addButton(self.push_ac)
        self.gridLayout_7.addWidget(self.push_ac, 3, 3, 1, 1)
        self.push_dot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_dot.sizePolicy().hasHeightForWidth())
        self.push_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_dot.setFont(font)
        self.push_dot.setObjectName("push_dot")
        self.buttons.addButton(self.push_dot)
        self.gridLayout_7.addWidget(self.push_dot, 8, 1, 1, 1)
        self.push_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_6.sizePolicy().hasHeightForWidth())
        self.push_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_6.setFont(font)
        self.push_6.setObjectName("push_6")
        self.buttons.addButton(self.push_6)
        self.gridLayout_7.addWidget(self.push_6, 6, 2, 1, 1)
        self.push_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_8.sizePolicy().hasHeightForWidth())
        self.push_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_8.setFont(font)
        self.push_8.setObjectName("push_8")
        self.buttons.addButton(self.push_8)
        self.gridLayout_7.addWidget(self.push_8, 5, 1, 1, 1)
        self.push_result = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_result.sizePolicy().hasHeightForWidth())
        self.push_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_result.setFont(font)
        self.push_result.setObjectName("push_result")
        self.buttons.addButton(self.push_result)
        self.gridLayout_7.addWidget(self.push_result, 7, 4, 2, 1)
        self.push_bracket_left = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_bracket_left.sizePolicy().hasHeightForWidth())
        self.push_bracket_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_bracket_left.setFont(font)
        self.push_bracket_left.setObjectName("push_bracket_left")
        self.buttons.addButton(self.push_bracket_left)
        self.gridLayout_7.addWidget(self.push_bracket_left, 3, 0, 1, 1)
        self.push_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_0.sizePolicy().hasHeightForWidth())
        self.push_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_0.setFont(font)
        self.push_0.setObjectName("push_0")
        self.buttons.addButton(self.push_0)
        self.gridLayout_7.addWidget(self.push_0, 8, 0, 1, 1)
        self.push_c = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_c.sizePolicy().hasHeightForWidth())
        self.push_c.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_c.setFont(font)
        self.push_c.setObjectName("push_c")
        self.buttons.addButton(self.push_c)
        self.gridLayout_7.addWidget(self.push_c, 3, 2, 1, 1)
        self.push_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_9.sizePolicy().hasHeightForWidth())
        self.push_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_9.setFont(font)
        self.push_9.setObjectName("push_9")
        self.buttons.addButton(self.push_9)
        self.gridLayout_7.addWidget(self.push_9, 5, 2, 1, 1)
        self.push_del = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_del.sizePolicy().hasHeightForWidth())
        self.push_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_del.setFont(font)
        self.push_del.setObjectName("push_del")
        self.buttons.addButton(self.push_del)
        self.gridLayout_7.addWidget(self.push_del, 3, 4, 1, 1)
        self.push_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_3.sizePolicy().hasHeightForWidth())
        self.push_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_3.setFont(font)
        self.push_3.setObjectName("push_3")
        self.buttons.addButton(self.push_3)
        self.gridLayout_7.addWidget(self.push_3, 7, 2, 1, 1)
        self.push_bracket_right = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_bracket_right.sizePolicy().hasHeightForWidth())
        self.push_bracket_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_bracket_right.setFont(font)
        self.push_bracket_right.setObjectName("push_bracket_right")
        self.buttons.addButton(self.push_bracket_right)
        self.gridLayout_7.addWidget(self.push_bracket_right, 3, 1, 1, 1)
        self.push_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_7.sizePolicy().hasHeightForWidth())
        self.push_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_7.setFont(font)
        self.push_7.setObjectName("push_7")
        self.buttons.addButton(self.push_7)
        self.gridLayout_7.addWidget(self.push_7, 5, 0, 1, 1)
        self.push_minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_minus.sizePolicy().hasHeightForWidth())
        self.push_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_minus.setFont(font)
        self.push_minus.setObjectName("push_minus")
        self.buttons.addButton(self.push_minus)
        self.gridLayout_7.addWidget(self.push_minus, 7, 3, 1, 1)
        self.push_divide = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_divide.sizePolicy().hasHeightForWidth())
        self.push_divide.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_divide.setFont(font)
        self.push_divide.setObjectName("push_divide")
        self.buttons.addButton(self.push_divide)
        self.gridLayout_7.addWidget(self.push_divide, 5, 3, 1, 1)
        self.push_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_5.sizePolicy().hasHeightForWidth())
        self.push_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.push_5.setFont(font)
        self.push_5.setObjectName("push_5")
        self.buttons.addButton(self.push_5)
        self.gridLayout_7.addWidget(self.push_5, 6, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_copy = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_copy.sizePolicy().hasHeightForWidth())
        self.push_copy.setSizePolicy(sizePolicy)
        self.push_copy.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_copy.setFont(font)
        self.push_copy.setFlat(False)
        self.push_copy.setObjectName("push_copy")
        self.horizontalLayout.addWidget(self.push_copy)
        self.result = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result.sizePolicy().hasHeightForWidth())
        self.result.setSizePolicy(sizePolicy)
        self.result.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.result.setFont(font)
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setReadOnly(True)
        self.result.setObjectName("result")
        self.horizontalLayout.addWidget(self.result)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.expression = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expression.sizePolicy().hasHeightForWidth())
        self.expression.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.expression.setFont(font)
        self.expression.setStyleSheet("")
        self.expression.setText("")
        self.expression.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.expression.setObjectName("expression")
        self.verticalLayout_3.addWidget(self.expression)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 20))
        self.menubar.setObjectName("menubar")
        self.menupycccalc = QtWidgets.QMenu(self.menubar)
        self.menupycccalc.setObjectName("menupycccalc")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menupycccalc.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyCCCalc"))
        self.push_1.setToolTip(_translate("MainWindow", "One"))
        self.push_1.setText(_translate("MainWindow", "1"))
        self.push_4.setToolTip(_translate("MainWindow", "Four"))
        self.push_4.setText(_translate("MainWindow", "4"))
        self.push_plus.setToolTip(_translate("MainWindow", "Plus"))
        self.push_plus.setText(_translate("MainWindow", "+"))
        self.push_multiply.setToolTip(_translate("MainWindow", "Multiply"))
        self.push_multiply.setText(_translate("MainWindow", "*"))
        self.push_2.setToolTip(_translate("MainWindow", "Two"))
        self.push_2.setText(_translate("MainWindow", "2"))
        self.push_ac.setToolTip(_translate("MainWindow", "All Clear"))
        self.push_ac.setText(_translate("MainWindow", "AC"))
        self.push_dot.setToolTip(_translate("MainWindow", "Decimal point"))
        self.push_dot.setText(_translate("MainWindow", "."))
        self.push_6.setToolTip(_translate("MainWindow", "Six"))
        self.push_6.setText(_translate("MainWindow", "6"))
        self.push_8.setToolTip(_translate("MainWindow", "Eight"))
        self.push_8.setText(_translate("MainWindow", "8"))
        self.push_result.setToolTip(_translate("MainWindow", "Equals"))
        self.push_result.setText(_translate("MainWindow", "="))
        self.push_bracket_left.setToolTip(_translate("MainWindow", "Open Bracket"))
        self.push_bracket_left.setText(_translate("MainWindow", "("))
        self.push_0.setToolTip(_translate("MainWindow", "Zero"))
        self.push_0.setText(_translate("MainWindow", "0"))
        self.push_c.setToolTip(_translate("MainWindow", "Clear"))
        self.push_c.setText(_translate("MainWindow", "C"))
        self.push_9.setToolTip(_translate("MainWindow", "Nine"))
        self.push_9.setText(_translate("MainWindow", "9"))
        self.push_del.setToolTip(_translate("MainWindow", "Delete last character"))
        self.push_del.setText(_translate("MainWindow", "Del"))
        self.push_3.setToolTip(_translate("MainWindow", "Three"))
        self.push_3.setText(_translate("MainWindow", "3"))
        self.push_bracket_right.setToolTip(_translate("MainWindow", "Close Bracket"))
        self.push_bracket_right.setText(_translate("MainWindow", ")"))
        self.push_7.setToolTip(_translate("MainWindow", "Seven"))
        self.push_7.setText(_translate("MainWindow", "7"))
        self.push_minus.setToolTip(_translate("MainWindow", "Minus"))
        self.push_minus.setText(_translate("MainWindow", "-"))
        self.push_divide.setToolTip(_translate("MainWindow", "Divide"))
        self.push_divide.setText(_translate("MainWindow", "/"))
        self.push_5.setToolTip(_translate("MainWindow", "Five"))
        self.push_5.setText(_translate("MainWindow", "5"))
        self.push_copy.setToolTip(_translate("MainWindow", "Copy to clipboard"))
        self.push_copy.setText(_translate("MainWindow", "C"))
        self.result.setToolTip(_translate("MainWindow", "Result"))
        self.result.setText(_translate("MainWindow", "0"))
        self.result.setPlaceholderText(_translate("MainWindow", "result"))
        self.expression.setToolTip(_translate("MainWindow", "Expression"))
        self.expression.setPlaceholderText(_translate("MainWindow", "expression"))
        self.menupycccalc.setTitle(_translate("MainWindow", "pycccalc"))


